# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a4dcb048cc5696254ca91d15cf6b3cbed2fc1594a038e1189ac9af8b2fba3356b129e6f76d5ff266b441e54f9df5ea55e4aaaf6cdcf880bbe0d77134b4a5e610

test:
  secret_key_base: ed0c9241a389dbbae369e995a97cd02fc61534e3de5163698e9109babcad1c9ae03f3ef7b73f916a2096a2d339568b7fb68f9d1e11c479b23070aa121fee31e5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
